decodeSVMResult:
	g++ decodeSVMResult.cpp -std=c++0x -O2 -o decodeSVMResult.out
getNegWord:
	g++ getNegKeyword.cpp -std=c++0x -lpthread -I/usr/local/scws/include/scws -L/usr/local/scws/lib -lscws -Wl,--rpath -Wl,/usr/local/scws/lib -o ./getNegKeyword.out
svmPre:
	g++ svmPreprocess.cpp -O2 -o svmPreprocess.out
